### ISSUE TITLE
Handle more escape codes

### ISSUE THREAD

**Issue by rgbkrk** [nteract/ansi-to-react#2] opened 2016-03-29 19:01 UTC
This is partially a duplicate of https://github.com/IonicaBizau/ansi-to-json/issues/2 with a bit more. The escape codes I definitely want to support are related to clearing (which needs to know the line). As brought up in https://github.com/sourcelair/xterm.js/issues/48, we'd like to reduce:

<img width="775" alt="screenshot 2016-03-29 09 16 24" src="https://cloud.githubusercontent.com/assets/836375/14117087/d8272f02-f597-11e5-849d-386c985fbfab.png">

to this:

<img width="779" alt="screenshot 2016-03-29 10 20 57" src="https://cloud.githubusercontent.com/assets/836375/14117094/e1177216-f597-11e5-848c-2549c8ecc56e.png">

**Comment by jerch** [comment] 2016-05-03 14:45
As soon as you want more than dumb terminal functionality you gonna have to fire up a smart terminal emulator in the background to hold the state between consecutive stream outputs (output always depends on former output).
Dumb terminals on the other hand work similar to real teletypewriters (TTY), best they can do is LF and CR for cursor and line manipulation, which makes data processing line by line pretty easy - they never gonna try to jump back. Therefore the stream output is independent as soon as a new line starts. (see https://en.wikipedia.org/wiki/Computer_terminal#Dumb_terminals)
From here you can either go with the rich output and a smart emulator or try to degrade the pty to a dumb device. Not sure if the latter will work for you since it will disable all the nifty output for most unix commandline tools. Working with a smart emulator will raise user experience a lot but also needs much much more coding.

**Comment by rgbkrk** [comment] 2016-05-03 16:31
Thanks @jerch! I've been digging into a few of the forks of term.js, wondering about a separation of the state of the terminal without a view (solely the model of the smart terminal).

Would you want to hack on this?

**Comment by jerch** [comment] 2016-05-04 07:08
I started an offscreen emulator in vanilla javascript some time ago (see https://github.com/netzkolchose/node-ansiterminal) but kinda got stuck when I implemented double width and combining character support. It comes with a functionality test suite based on xterm output. Though tons of xterm features are still missing everyday basic stuff like cursor positioning, resizing and colors works, as you can test with the quick'n dirty jquery frontend here https://github.com/netzkolchose/jquery.browserterminal

Maybe this will suit your purpose, if so I can get my hands dirty trying to remove the alpha flag.

**Comment by rgbkrk** [comment] 2016-05-04 15:17
Oooh, that's looking good for the offscreen model. It will be nice to use that as terminal stream is coming in. I'll probably keep that separate from this component and use it direct in https://github.com/nteract/nteract.

**Comment by jerch** [comment] 2016-05-22 01:19
I did some refactoring of the terminal emulator. Maybe you will find the example in https://github.com/netzkolchose/node-ansiterminal/blob/master/examples/tools.js useful.

**Comment by IonicaBizau** [comment] 2016-09-26 07:44
@rgbkrk Is this still a thing? Should I fix it in anser or did you decide using another module in the end?

Styles are available in `anser` now, /cc https://github.com/IonicaBizau/ansi-to-json/issues/2

**Comment by rgbkrk** [comment] 2016-09-26 11:13
Still a thing. Thanks for tackling it.

**Comment by IonicaBizau** [comment] 2016-09-26 11:13
@rgbkrk So, should we fix it in `anser`?

**Comment by rgbkrk** [comment] 2016-09-26 11:16
I'd love to fix it higher up so that streaming output in the notebook reduces to a smaller string that we store in the notebook document.

**Comment by IonicaBizau** [comment] 2016-09-26 11:18
@rgbkrk Makes sense. If you need help with a library for that, I may be able to help. 😁

**Comment by rgbkrk** [comment] 2016-09-26 11:20
Totally.

**Comment by lgeiger** [comment] 2020-05-26 17:32
I just checked with the latest version of nteract and it seems when executing `!npm install browserify` the progressbar is rendered correctly.

I will close this issue. Feel free to reopen if I am missing something :)

**Closed by lgeiger** 2020-05-26 17:32 UTC

**Comment by jerch** [comment] 2020-05-27 19:59
@lgeiger Well I am not sure, if this implemented with the correct behavior in the upstream lib - a '\r' should technically only move the cursor to the left allowing overprinting, not erasing the content thats already on the line.
But since the issue is quite old and it seems to work for you, it is prolly good enough for your use cases.
